# Generated by Django 4.2.4 on 2023-08-20 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_alter_mailinglogs_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailinglogs',
            name='client',
        ),
        migrations.AddField(
            model_name='mailinglogs',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='mailings.client', verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
