# Generated by Django 4.2.4 on 2023-08-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0003_remove_mailinglogs_client_mailinglogs_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglogs',
            name='mail_server_response',
            field=models.BooleanField(verbose_name='Ответ почтового сервера'),
        ),
    ]
