# Generated by Django 4.2.4 on 2023-09-17 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0005_client_owner_mailing_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'permissions': [('set_status', 'Can change status')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
    ]
